[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_movie_review_program = "7QokLGDkRajYY99oBVZqhXbuo9jMWDGLitoBux1MeDYp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
